### ISSUE TITLE
Link to Purchase / Download Sites

### ISSUE THREAD

**Issue by jalcine** [blkops/Reading-and-Context-on-Race#1]
It'll be a pain in the ass to get started and I wish I saw this sooner, but we could provide a link to [Goodreads](https://goodreads.com) or directly to Amazon itself. I can start on this, but seeing as how you've put in so much work, I want to know if you consider it worthwhile.

**Comment by Blucka12** [comment]
Sounds good! I'm not attached to what I put up or how it was structured. I just wanted something legible to start.

Link away!

Oak Ritchie
(843) 625-1567
www.steadyflowblog.com

**Comment by jalcine** [comment]
I'll start on this either later tonight or tomorrow evening.

**Comment by ohpeacock** [comment]
@jalcine, I can help you out with this! Do you think a link to GoodReads would be better or just linking this text would work?

**Comment by jalcine** [comment]
@odorsey Linking to the book on Goodreads would be dope, allows people to do a quick purchase and what not.

**Comment by ohpeacock** [comment]
Okay, GoodReads then :smile:

**Comment by jalcine** [comment]
Dope! Sorry, I took an early sleep yesterday.

**Comment by ohpeacock** [comment]
DONE :wink:

**Comment by jalcine** [comment]
@odorsey you're the MVP :8ball: 

_edited_: gender neutral up in here.

**Comment by ohpeacock** [comment]
haha thanks, @jalcine! :+1:
